In [31]:
import pandas as pd
import numpy as np
import warnings
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn import svm
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix, classification_report
warnings.filterwarnings("ignore")

In [18]:
insdf = pd.read_csv("CarInsurance.csv")

In [19]:
insdf.head()

,ID,MOSTYPE,MAANTHUI,MGEMOMV,MGEMLEEF,MOSHOOFD,MGODRK,MGODPR,MGODOV,MGODGE,...,APERSONG,AGEZONG,AWAOREG,ABRAND,AZEILPL,APLEZIER,AFIETS,AINBOED,ABYSTAND,Purchase
0,1,33,1,3,2,8,0,5,1,3,...,0,0,0,1,0,0,0,0,0,No
1,2,37,1,2,2,8,1,4,1,4,...,0,0,0,1,0,0,0,0,0,No
2,3,37,1,2,2,8,0,4,2,4,...,0,0,0,1,0,0,0,0,0,No
3,4,9,1,3,3,3,2,3,2,4,...,0,0,0,1,0,0,0,0,0,No
4,5,40,1,4,2,10,1,4,1,4,...,0,0,0,1,0,0,0,0,0,No

In [20]:
insdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5822 entries, 0 to 5821
Data columns (total 87 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        5822 non-null   int64
 1   MOSTYPE   5822 non-null   int64
 2   MAANTHUI  5822 non-null   int64
 3   MGEMOMV   5822 non-null   int64
 4   MGEMLEEF  5822 non-null   int64
 5   MOSHOOFD  5822 non-null   int64
 6   MGODRK    5822 non-null   int64
 7   MGODPR    5822 non-null   int64
 8   MGODOV    5822 non-null   int64
 9   MGODGE    5822 non-null   int64
 10  MRELGE    5822 non-null   int64
 11  MRELSA    5822 non-null   int64
 12  MRELOV    5822 non-null   int64
 13  MFALLEEN  5822 non-null   int64
 14  MFGEKIND  5822 non-null   int64
 15  MFWEKIND  5822 non-null   int64
 16  MOPLHOOG  5822 non-null   int64
 17  MOPLMIDD  5822 non-null   int64
 18  MOPLLAAG  5822 non-null   int64
 19  MBERHOOG  5822 non-null   int64
 20  MBERZELF  5822 non-null   int64
 21  MBERBOER  5822 non-null   int64
 22  MBERMIDD  5822 non-null   int64
 23  MBERARBG  5822 non-null   int64
 24  MBERARBO  5822 non-null   int64
 25  MSKA      5822 non-null   int64
 26  MSKB1     5822 non-null   int64
 27  MSKB2     5822 non-null   int64
 28  MSKC      5822 non-null   int64
 29  MSKD      5822 non-null   int64
 30  MHHUUR    5822 non-null   int64
 31  MHKOOP    5822 non-null   int64
 32  MAUT1     5822 non-null   int64
 33  MAUT2     5822 non-null   int64
 34  MAUT0     5822 non-null   int64
 35  MZFONDS   5822 non-null   int64
 36  MZPART    5822 non-null   int64
 37  MINKM30   5822 non-null   int64
 38  MINK3045  5822 non-null   int64
 39  MINK4575  5822 non-null   int64
 40  MINK7512  5822 non-null   int64
 41  MINK123M  5822 non-null   int64
 42  MINKGEM   5822 non-null   int64
 43  MKOOPKLA  5822 non-null   int64
 44  PWAPART   5822 non-null   int64
 45  PWABEDR   5822 non-null   int64
 46  PWALAND   5822 non-null   int64
 47  PPERSAUT  5822 non-null   int64
 48  PBESAUT   5822 non-null   int64
 49  PMOTSCO   5822 non-null   int64
 50  PVRAAUT   5822 non-null   int64
 51  PAANHANG  5822 non-null   int64
 52  PTRACTOR  5822 non-null   int64
 53  PWERKT    5822 non-null   int64
 54  PBROM     5822 non-null   int64
 55  PLEVEN    5822 non-null   int64
 56  PPERSONG  5822 non-null   int64
 57  PGEZONG   5822 non-null   int64
 58  PWAOREG   5822 non-null   int64
 59  PBRAND    5822 non-null   int64
 60  PZEILPL   5822 non-null   int64
 61  PPLEZIER  5822 non-null   int64
 62  PFIETS    5822 non-null   int64
 63  PINBOED   5822 non-null   int64
 64  PBYSTAND  5822 non-null   int64
 65  AWAPART   5822 non-null   int64
 66  AWABEDR   5822 non-null   int64
 67  AWALAND   5822 non-null   int64
 68  APERSAUT  5822 non-null   int64
 69  ABESAUT   5822 non-null   int64
 70  AMOTSCO   5822 non-null   int64
 71  AVRAAUT   5822 non-null   int64
 72  AAANHANG  5822 non-null   int64
 73  ATRACTOR  5822 non-null   int64
 74  AWERKT    5822 non-null   int64
 75  ABROM     5822 non-null   int64
 76  ALEVEN    5822 non-null   int64
 77  APERSONG  5822 non-null   int64
 78  AGEZONG   5822 non-null   int64
 79  AWAOREG   5822 non-null   int64
 80  ABRAND    5822 non-null   int64
 81  AZEILPL   5822 non-null   int64
 82  APLEZIER  5822 non-null   int64
 83  AFIETS    5822 non-null   int64
 84  AINBOED   5822 non-null   int64
 85  ABYSTAND  5822 non-null   int64
 86  Purchase  5822 non-null   object
dtypes: int64(86), object(1)
memory usage: 3.9+ MB

In [21]:
#Checking for missing values in the dataset
insdf[insdf.isna().any(1)]

Empty DataFrame
Columns: [ID, MOSTYPE, MAANTHUI, MGEMOMV, MGEMLEEF, MOSHOOFD, MGODRK, MGODPR, MGODOV, MGODGE, MRELGE, MRELSA, MRELOV, MFALLEEN, MFGEKIND, MFWEKIND, MOPLHOOG, MOPLMIDD, MOPLLAAG, MBERHOOG, MBERZELF, MBERBOER, MBERMIDD, MBERARBG, MBERARBO, MSKA, MSKB1, MSKB2, MSKC, MSKD, MHHUUR, MHKOOP, MAUT1, MAUT2, MAUT0, MZFONDS, MZPART, MINKM30, MINK3045, MINK4575, MINK7512, MINK123M, MINKGEM, MKOOPKLA, PWAPART, PWABEDR, PWALAND, PPERSAUT, PBESAUT, PMOTSCO, PVRAAUT, PAANHANG, PTRACTOR, PWERKT, PBROM, PLEVEN, PPERSONG, PGEZONG, PWAOREG, PBRAND, PZEILPL, PPLEZIER, PFIETS, PINBOED, PBYSTAND, AWAPART, AWABEDR, AWALAND, APERSAUT, ABESAUT, AMOTSCO, AVRAAUT, AAANHANG, ATRACTOR, AWERKT, ABROM, ALEVEN, APERSONG, AGEZONG, AWAOREG, ABRAND, AZEILPL, APLEZIER, AFIETS, AINBOED, ABYSTAND, Purchase]
Index: []

[0 rows x 87 columns]

In [22]:
insdf.groupby(["Purchase"]).count()

,ID,MOSTYPE,MAANTHUI,MGEMOMV,MGEMLEEF,MOSHOOFD,MGODRK,MGODPR,MGODOV,MGODGE,...,ALEVEN,APERSONG,AGEZONG,AWAOREG,ABRAND,AZEILPL,APLEZIER,AFIETS,AINBOED,ABYSTAND
Purchase,,,,,,,,,,,,,,,,,,,,,
No,5474,5474,5474,5474,5474,5474,5474,5474,5474,5474,...,5474,5474,5474,5474,5474,5474,5474,5474,5474,5474
Yes,348,348,348,348,348,348,348,348,348,348,...,348,348,348,348,348,348,348,348,348,348

In [23]:
insdf = insdf.drop(labels = "ID", axis = 1)

In [24]:
array = insdf.values
X = array[:,0:85]
Y = array[:,85]
test_size = 0.30 # taking 70:30 training and test set
seed = 10  # Random numbmer seeding for reapeatability of the code
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)
type(X_train)

numpy.ndarray

In [50]:
#Method to generate Confusion matric and Classfication Report
def evaluate_model(y_test,y_predict):
    cm = confusion_matrix(y_test, y_predict)
    cr = classification_report(y_test, y_predict)
    return cm,cr

In [52]:
# LogisticRegression
Lmodel = LogisticRegression()
Lmodel.fit(X_train, y_train)
y_predict = Lmodel.predict(X_test)
Lmodel_score = Lmodel.score(X_test, y_test)
Lcm,Lcr = evaluate_model(y_test,y_predict)
print("Accuracy Score : {}".format(Lmodel_score))
print("Confusion Matrix : \n{}".format(Lcm))
print("Classification Report : \n{}".format(Lcr))

Accuracy Score : 0.9393245563823698
Confusion Matrix :
[[1641    6]
 [ 100    0]]
Classification Report :
              precision    recall  f1-score   support

          No       0.94      1.00      0.97      1647
         Yes       0.00      0.00      0.00       100

    accuracy                           0.94      1747
   macro avg       0.47      0.50      0.48      1747
weighted avg       0.89      0.94      0.91      1747

In [53]:
# Naive Bayes
Nmodel=GaussianNB()
Nmodel.fit(X_train,y_train)
y_predict=Nmodel.predict(X_test)
Nmodel_score = accuracy_score(y_test,y_predict)
Ncm,Ncr = evaluate_model(y_test,y_predict)
print("Accuracy Score : {}".format(Nmodel_score))
print("Confusion Matrix : \n{}".format(Ncm))
print("Classification Report : \n{}".format(Ncr))

Accuracy Score : 0.1001717229536348
Confusion Matrix :
[[  77 1570]
 [   2   98]]
Classification Report :
              precision    recall  f1-score   support

          No       0.97      0.05      0.09      1647
         Yes       0.06      0.98      0.11       100

    accuracy                           0.10      1747
   macro avg       0.52      0.51      0.10      1747
weighted avg       0.92      0.10      0.09      1747

In [54]:
# KNeighborsClassifier
NNH = KNeighborsClassifier(n_neighbors= 21 , weights = 'uniform', metric='euclidean')
NNH.fit(X_train, y_train)
y_predict = NNH.predict(X_test)
Kmodel_score = accuracy_score(y_test,y_predict)
Kcm,Kcr = evaluate_model(y_test,y_predict)
print("Accuracy Score : {}".format(Kmodel_score))
print("Confusion Matrix : \n{}".format(Kcm))
print("Classification Report : \n{}".format(Kcr))

Accuracy Score : 0.9427590154550658
Confusion Matrix :
[[1647    0]
 [ 100    0]]
Classification Report :
              precision    recall  f1-score   support

          No       0.94      1.00      0.97      1647
         Yes       0.00      0.00      0.00       100

    accuracy                           0.94      1747
   macro avg       0.47      0.50      0.49      1747
weighted avg       0.89      0.94      0.91      1747

In [55]:
# Support Vector Machine
svmModel = svm.SVC(kernel = 'linear', C = 100)
svmModel.fit(X_train,y_train)
y_predict = svmModel.predict(X_test)
Smodel_score = accuracy_score(y_test,y_predict)
Scm,Scr = evaluate_model(y_test,y_predict)
print("Accuracy Score : {}".format(Smodel_score))
print("Confusion Matrix : \n{}".format(Scm))
print("Classification Report : \n{}".format(Scr))

Accuracy Score : 0.9427590154550658
Confusion Matrix :
[[1647    0]
 [ 100    0]]
Classification Report :
              precision    recall  f1-score   support

          No       0.94      1.00      0.97      1647
         Yes       0.00      0.00      0.00       100

    accuracy                           0.94      1747
   macro avg       0.47      0.50      0.49      1747
weighted avg       0.89      0.94      0.91      1747

In [ ]:
#The best model for the test data is KNeighborsClassifier model
    #as it is the simplest of all models and the model that should be 
    #preferred incase of labelled data and it has high accuracy scored of 94 %.